version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo Building project
      - mvn package
  test:
    commands:
      - echo Running tests
      - mvn test

artifacts:
  files:
    - target/*.jar
